### ISSUE TITLE
#include "gtest\gtest.h" fails with travis.

### ISSUE THREAD

**Issue by fumoffu947** [holmgr/dsa-cozy-corner#11]
On my computer all the tests pass. But when i uploaded the code, Travis failed on the include of gtest.
See the Travis CI build # 53

**Comment by holmgr** [comment]
Problem lies in using the wrong type of slashes for cross platform (Unix) includes. You need: ````
```cpp
#include "gtest/gtest.h"
```
ie. a `/` not a `\`

Should solve your issues :)

**Comment by fumoffu947** [comment]
Yes that was the problem.
